name: Build Source

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: yarn install

      - name: Compile files
        run: yarn build

      - name: Commit Files
        continue-on-error: true # commit will fail if the code wasn't changed. Prevent the build to fail in this case.
        run: |
          git config --local user.email "admin@moropo.com"
          git config --local user.name "Moropo"

          git add dist/index.js -f
          git commit -m "[CI] Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
