name: Moropo Test Run
on:
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Moropo Tests
        uses: moropo-com/action-trigger-test-run@updating-gh-comments
        with:
          scheduled_test_id: 04f1acb4-c4d5-4389-b31e-55002a2ae059
          api_key: f81ba9de-7a49-4f04-a907-f27ca83b886a
          expo_release_channel: https://u.expo.dev/cd0e344b-8011-4434-91a6-dec86deb68c0?channel-name=moropo-410&runtime-version=exposdk:47.0.0&platform=android&disableOnboarding=1
          build_path: builds/ios.app.zip
          moropo_url: https://dev.moropo.com/
